merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name = 'band-detail'),
    path('about-us/', views.about, name='aboutus'),
    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>', views.listing_detail, name='listing-detail'),
    path('contact-us/', views.contact, name='contact'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    def __str__(self) -> str:
        return f"{self.name}"
    
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

class Listing(models.Model):

    def __str__(self) -> str:
        return f"{self.title}"
    
    class Type(models.TextChoices):
        Records = 'records'
        Clothing = 'clothing'
        Posters = 'posters'
        Miscellaneous = 'miscellaneous'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2024)])
    type = models.fields.CharField(choices=Type.choices, max_length=100)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band, Listing
from listings.forms import ContactUsForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})

def band_detail(request, id):
   band = Band.objects.get(id=id)
   return render(request,
          'listings/band_detail.html',
         {'band': band})

def about(request):
    return render(request, 'listings/about.html')

def listing_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing_list.html', {'listings': listings})

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
          'listings/listing_detail.html',
         {'listing': listing})

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
            return redirect('email-sent')
    else:
        form = ContactUsForm()

    return render(request,
            'listings/contact.html',
            {'form': form})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>À propos de Merchex</h1>
<p>MerchEx est une application qui vous permet d'échanger et d'acheter des objets.</p>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_homepage %}
 <li>Page officielle : <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
 {% endif %}

<p>{{ band.biography }}</p>
<a href="{% url 'band-list' %}">Retour</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Groupes</h1>
<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/base.html
<html>
    <head><title>Merchex</title></head>
    <body>
    <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'listing-list' %}">Produits</a>
        <a href="{% url 'aboutus' %}">A propos de nous</a>
        <a href="{% url 'contact' %}">Contact</a>
    </nav>

    {% block content %}{% endblock %}

    </body>
    <footer>
        <p>&copy; 2024 MerchEx. Tous droits réservés.</p>
    </footer>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}
{% block content %}
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Hello Django !</h1>

<p>Mes groupes préférés sont :</p>

<ul>
    {% for band in bands %}
        <li>
            {{ band.name }}
        </li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.title }}</h2>

<ul>
 <li>Type : {{ listing.get_type_display }}</li>
 <li>Année : {{ listing.year }}</li>
 <li>Sold : {{ listing.sold|yesno }}</li>
 {% if listing.band %}
 <li>Band : {{ listing.band }}</li>
 {% endif %}

<p>{{ listing.description }}</p>
<a href="{% url 'listing-list' %}">Retour</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Liste</h1>

<p>Voici les articles disponibles :</p>
<ul>
    {% for listing in listings %}
    <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Liste</h1>

<p>Voici les articles disponibles :</p>
<ul>
    {% for listing in listings %}
    <li>{{ listing.title }}</li>
    {% endfor %}
</ul>
{% endblock}